[package]
name = "httpdt"
version = "0.1.0"
edition = "2021"
description = "datetime library for HTTP clients and servers"
keywords = ["datetime", "HTTP", "Date", "header", "GMT"]
authors = ["barcek"]
license = "MIT"
repository = "https://github.com/barcek/httpdt/"
